###
#   Tomcat Settings
###
server:
  port: 8080
messages:
  hello: Hello, Memory not found!



spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: none
    #      ddl-auto: validate
    #      ddl-auto: update
    #      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  thymeleaf:
    encoding: utf-8
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    # excluded-view-names:
    # mode: HTML5
#     prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names:
logging:
  level:
    - ".=info"
    - "com.memorynotfound=debug"
    - "org.springframework=info"





# Using for JSP
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp


